import { ArrowRight, CheckCircle2, ClipboardList } from "lucide-react";
import Link from "next/link";

const comparisons = [
  { label: "Citizen starting point", standard: "Write a free-form question and hope it reaches the right desk.", saarthi: "Turn plain language into a focused records request." },
  { label: "Legal clarity", standard: "Limited guidance on what Section 2(f) and 2(j) cover.", saarthi: "Identify existing records that are concrete, checkable, and less likely to be rejected." },
  { label: "Filing confidence", standard: "Find the authority, fee, and next step yourself.", saarthi: "Match the authority, run privacy and jurisdiction guards, then review before filing." },
];

export default function AboutPage() {
  return (
    <main className="min-h-screen bg-[#f5f1e8] text-[#173c38]"><div className="mx-auto flex min-h-screen w-full max-w-7xl flex-col px-6 py-6 sm:px-10 lg:px-14"><header className="flex items-center justify-between border-b border-[#173c38]/15 pb-5"><Link href="/" className="flex items-center gap-3"><div className="flex size-10 items-center justify-center rounded-xl bg-[#173c38] text-[#f5f1e8]"><ClipboardList size={20} /></div><div><p className="text-sm font-bold tracking-[0.16em] uppercase">RTI Saarthi</p><p className="text-xs text-[#173c38]/60">Citizen Intelligence &amp; RTI Filing Layer</p></div></Link><Link href="/" className="text-sm font-bold text-[#c45b35] hover:underline">Back to home</Link></header><section className="mx-auto w-full max-w-5xl py-14 lg:py-20"><p className="mb-7 text-sm font-semibold text-[#c45b35]">About RTI Saarthi</p><h1 className="max-w-4xl text-5xl leading-[0.98] font-semibold tracking-[-0.04em] sm:text-7xl">Make the question clearer. Make the answer checkable.</h1><p className="mt-8 max-w-3xl text-xl leading-9 text-[#173c38]/70">Transforming plain-language citizen inquiries into valid, structured record requests to eliminate rejections under Section 2(f) and 2(j).</p><div className="mt-14 overflow-hidden rounded-2xl border border-[#173c38]/10 bg-[#fffdf8] shadow-[0_20px_45px_rgba(23,60,56,0.08)]"><div className="grid grid-cols-[1fr_1fr] border-b border-[#173c38]/10 bg-[#e5eee4] px-5 py-4 text-xs font-bold tracking-[0.12em] uppercase sm:grid-cols-[1fr_1fr_1fr]"><span>Workflow</span><span>rtionline.gov.in</span><span>RTI Saarthi</span></div>{comparisons.map((comparison) => <div key={comparison.label} className="grid grid-cols-[1fr_1fr] gap-x-5 border-b border-[#173c38]/10 px-5 py-5 last:border-0 sm:grid-cols-[1fr_1fr_1fr]"><p className="col-span-2 text-sm font-bold sm:col-span-1">{comparison.label}</p><p className="mt-2 text-sm leading-6 text-[#173c38]/60 sm:mt-0">{comparison.standard}</p><p className="mt-3 flex gap-2 text-sm leading-6 text-[#173c38]/80 sm:mt-0"><CheckCircle2 className="mt-0.5 shrink-0 text-[#27745e]" size={17} />{comparison.saarthi}</p></div>)}</div><div className="mt-10 flex flex-col gap-4 rounded-2xl bg-[#173c38] p-6 text-[#f5f1e8] sm:flex-row sm:items-center sm:justify-between"><p className="max-w-2xl text-lg leading-7">RTI Saarthi helps you ask for records. It does not promise outcomes or replace official filing channels.</p><Link href="/" className="flex min-h-12 shrink-0 items-center justify-center gap-2 rounded-xl bg-[#c45b35] px-5 py-3 text-sm font-bold transition hover:bg-[#a94728]">Ask a question <ArrowRight size={17} /></Link></div></section></div></main>
  );
}
