"use client";

import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";

export type LanguageCode = "en" | "hi" | "bn" | "te" | "mr" | "ta" | "gu" | "kn" | "ml" | "pa";
export type TranslationKey = "portal_title" | "brand_title" | "header_subtitle" | "checks_enabled" | "about" | "live_alert_badge" | "live_alert" | "screen_1_badge" | "hero_title" | "hero_sub" | "input_label" | "placeholder" | "btn_continue" | "btn_analyze" | "need_more_detail" | "question_clear" | "validation_clear_detail" | "recent_inquiries" | "clarity_card" | "faq_desk_btn" | "try_sample" | "sample_chip_road" | "sample_chip_pension" | "sample_chip_scholarship" | "sample_chip_water" | "your_records" | "records_count" | "item_road_title" | "item_road_dept" | "item_scholarship_title" | "item_scholarship_dept" | "item_water_title" | "item_water_dept" | "built_for_clarity";

type TranslationDictionary = Record<TranslationKey, string>;

const translations: Record<LanguageCode, TranslationDictionary> = {
  en: {
    portal_title: "Citizen Services Portal", brand_title: "RTI SAARTHI", header_subtitle: "Citizen Intelligence & RTI Filing Layer", checks_enabled: "Deterministic checks enabled", about: "About RTI Saarthi", live_alert_badge: "LIVE ALERT", live_alert: "Statutory Alert: Section 7(1) mandates a 30-day response window. Do not attach Aadhaar or PAN numbers.", screen_1_badge: "Screen 1 / Ask a question", hero_title: "Ask the government with clarity.", hero_sub: "Convert plain-language questions into clear, structured RTI requests and guide citizens through the process.", input_label: "What would you like to find out?", placeholder: "For example: What is the status of the road repair tender in Ward 4, or why is my merit scholarship delayed?", btn_continue: "Continue", btn_analyze: "Analyze Request", need_more_detail: "Add more detail", question_clear: "Question looks clear", validation_clear_detail: "It contains a public-records topic and enough detail to search the records.", recent_inquiries: "Recent Public Inquiries", clarity_card: "Every answer starts with a checkable question and a clear source.", faq_desk_btn: "💬 RTI Help Desk", try_sample: "Try a sample", sample_chip_road: "Road repair tender status & contractor file notings in Ward 4", sample_chip_pension: "My pension hasn't been credited for three months", sample_chip_scholarship: "National merit scholarship disbursement delay & sanction order", sample_chip_water: "Municipal water pipeline inspection report and timeline", your_records: "YOUR RECORDS", records_count: "3 records", item_road_title: "Ward 4 Road Tender Sanction", item_road_dept: "Public Works Department (PWD)", item_scholarship_title: "National Merit Scholarship Release Order", item_scholarship_dept: "Ministry of Education", item_water_title: "Municipal Water Supply Quality Report", item_water_dept: "Municipal Corporation", built_for_clarity: "BUILT FOR CLARITY",
  },
  hi: {
    portal_title: "नागरिक सेवा पोर्टल", brand_title: "आरटीआई सारथी", header_subtitle: "नागरिक आसूचना एवं आरटीआई आवेदन प्रणाली", checks_enabled: "सटीक नियम जांच सक्रिय", about: "आरटीआई सारथी के बारे में", live_alert_badge: "लाइव अलर्ट", live_alert: "वैधानिक चेतावनी: धारा 7(1) के तहत 30 दिनों में उत्तर अनिवार्य है। आधार या पैन नंबर संलग्न न करें।", screen_1_badge: "स्क्रीन 1 / प्रश्न पूछें", hero_title: "सरकार से स्पष्टता के साथ पूछें।", hero_sub: "अपनी सरल भाषा के प्रश्नों को सभी विभागों के लिए संरचित और कानूनी रूप से मान्य आरटीआई अनुरोधों में बदलें।", input_label: "आप क्या जानना चाहते हैं?", placeholder: "उदाहरण: वार्ड 4 में सड़क मरम्मत टेंडर की स्थिति क्या है, या मेरी मेरिट छात्रवृत्ति में देरी क्यों है?", btn_continue: "जारी रखें", btn_analyze: "अनुरोध का विश्लेषण करें", need_more_detail: "अधिक विवरण जोड़ें", question_clear: "प्रश्न स्पष्ट है", validation_clear_detail: "इसमें सार्वजनिक रिकॉर्ड का विषय और रिकॉर्ड खोजने के लिए पर्याप्त विवरण है।", recent_inquiries: "हाल की सार्वजनिक पूछताछ", clarity_card: "हर उत्तर एक जाँच योग्य सवाल और स्पष्ट स्रोत से शुरू होता है।", faq_desk_btn: "💬 आरटीआई सहायता डेस्क", try_sample: "एक नमूना आज़माएँ", sample_chip_road: "वार्ड 4 में सड़क मरम्मत टेंडर स्थिति एवं ठेकेदार फाइल नोटिंग्स", sample_chip_pension: "मेरी पेंशन तीन महीने से जमा नहीं हुई है", sample_chip_scholarship: "राष्ट्रीय मेरिट छात्रवृत्ति वितरण में देरी एवं स्वीकृति आदेश", sample_chip_water: "नगर निगम जल पाइपलाइन निरीक्षण रिपोर्ट एवं समयसीमा", your_records: "आपके रिकॉर्ड", records_count: "3 रिकॉर्ड", item_road_title: "वार्ड 4 सड़क टेंडर स्वीकृति", item_road_dept: "लोक निर्माण विभाग (PWD)", item_scholarship_title: "राष्ट्रीय मेरिट छात्रवृत्ति जारी आदेश", item_scholarship_dept: "शिक्षा मंत्रालय", item_water_title: "नगर जल आपूर्ति गुणवत्ता रिपोर्ट", item_water_dept: "नगर निगम", built_for_clarity: "स्पष्टता के लिए निर्मित",
  },
  bn: {
    portal_title: "নাগরিক পরিষেবা পোর্টাল", brand_title: "আরটিআই সারথী", header_subtitle: "নাগরিক তথ্য ও আরটিআই আবেদন স্তর", checks_enabled: "নির্ধারিত নিয়ম পরীক্ষা সক্রিয়", about: "আরটিআই সারথী সম্পর্কে", live_alert_badge: "সরাসরি সতর্কতা", live_alert: "বিধিবদ্ধ সতর্কবার্তা: ধারা 7(1) অনুযায়ী 30 দিনের মধ্যে উত্তর বাধ্যতামূলক। আধার বা প্যান নম্বর সংযুক্ত করবেন না।", screen_1_badge: "স্ক্রিন 1 / প্রশ্ন জিজ্ঞাসা করুন", hero_title: "স্পষ্টভাবে সরকারকে জিজ্ঞাসা করুন।", hero_sub: "সহজ ভাষার প্রশ্নকে সব বিভাগের জন্য কাঠামোবদ্ধ, আইনসম্মত আরটিআই অনুরোধে রূপান্তর করুন।", input_label: "আপনি কী জানতে চান?", placeholder: "উদাহরণ: ওয়ার্ড 4-এ রাস্তা মেরামতের টেন্ডারের অবস্থা কী, অথবা আমার মেধা বৃত্তিতে দেরি কেন?", btn_continue: "চালিয়ে যান", btn_analyze: "অনুরোধ বিশ্লেষণ করুন", need_more_detail: "আরও বিবরণ যোগ করুন", question_clear: "প্রশ্নটি স্পষ্ট", validation_clear_detail: "এতে জনসাধারণের রেকর্ডের বিষয় এবং রেকর্ড খোঁজার জন্য যথেষ্ট বিবরণ রয়েছে।", recent_inquiries: "সাম্প্রতিক জনসাধারণের অনুসন্ধান", clarity_card: "প্রতিটি উত্তর যাচাইযোগ্য প্রশ্ন এবং স্পষ্ট উৎস দিয়ে শুরু হয়।", faq_desk_btn: "💬 আরটিআই সহায়তা ডেস্ক", try_sample: "একটি নমুনা চেষ্টা করুন", sample_chip_road: "ওয়ার্ড 4-এ রাস্তা মেরামতের টেন্ডারের অবস্থা ও ঠিকাদারের ফাইল নোটিংস", sample_chip_pension: "আমার পেনশন 3 মাস ধরে জমা হয়নি", sample_chip_scholarship: "জাতীয় মেধা বৃত্তি বিতরণে বিলম্ব ও অনুমোদন আদেশ", sample_chip_water: "পৌর জল পাইপলাইন পরিদর্শন প্রতিবেদন ও সময়সীমা", your_records: "আপনার রেকর্ড", records_count: "3টি রেকর্ড", item_road_title: "ওয়ার্ড 4 রাস্তা টেন্ডার অনুমোদন", item_road_dept: "গণপূর্ত বিভাগ (PWD)", item_scholarship_title: "জাতীয় মেধা বৃত্তি প্রকাশের আদেশ", item_scholarship_dept: "শিক্ষা মন্ত্রণালয়", item_water_title: "পৌর জল সরবরাহের গুণমান প্রতিবেদন", item_water_dept: "পৌর কর্পোরেশন", built_for_clarity: "স্বচ্ছতার জন্য নির্মিত",
  },
  te: {
    portal_title: "పౌర సేవల పోర్టల్", brand_title: "ఆర్టీఐ సారథి", header_subtitle: "పౌర సమాచారం మరియు ఆర్టీఐ దాఖలు వ్యవస్థ", checks_enabled: "ఖచ్చితమైన నియమాల తనిఖీ సక్రియం", about: "ఆర్టీఐ సారథి గురించి", live_alert_badge: "ప్రత్యక్ష హెచ్చరిక", live_alert: "చట్టబద్ధమైన హెచ్చరిక: సెక్షన్ 7(1) ప్రకారం 30 రోజుల్లో సమాధానం ఇవ్వాలి. ఆధార్ లేదా పాన్ నంబర్లను జత చేయవద్దు.", screen_1_badge: "స్క్రీన్ 1 / ప్రశ్న అడగండి", hero_title: "ప్రభుత్వాన్ని స్పష్టతతో అడగండి.", hero_sub: "సాధారణ భాషలోని ప్రశ్నలను అన్ని శాఖల కోసం నిర్మిత, చట్టబద్ధమైన ఆర్టీఐ అభ్యర్థనలుగా మార్చండి.", input_label: "మీరు ఏమి తెలుసుకోవాలనుకుంటున్నారు?", placeholder: "ఉదాహరణ: వార్డు 4 రోడ్డు మరమ్మతు టెండర్ స్థితి ఏమిటి లేదా నా మెరిట్ స్కాలర్‌షిప్ ఎందుకు ఆలస్యమైంది?", btn_continue: "కొనసాగించండి", btn_analyze: "అభ్యర్థనను విశ్లేషించండి", need_more_detail: "మరింత వివరాలు జోడించండి", question_clear: "ప్రశ్న స్పష్టంగా ఉంది", validation_clear_detail: "ఇందులో ప్రజా రికార్డు అంశం మరియు రికార్డులను శోధించడానికి తగిన వివరాలు ఉన్నాయి.", recent_inquiries: "ఇటీవలి ప్రజా విచారణలు", clarity_card: "ప్రతి సమాధానం తనిఖీ చేయగల ప్రశ్న మరియు స్పష్టమైన మూలంతో మొదలవుతుంది.", faq_desk_btn: "💬 ఆర్టీఐ సహాయ కేంద్రం", try_sample: "ఒక నమూనాను ప్రయత్నించండి", sample_chip_road: "వార్డు 4 రోడ్డు మరమ్మతు టెండర్ స్థితి మరియు కాంట్రాక్టర్ ఫైల్ నోటింగ్స్", sample_chip_pension: "నా పెన్షన్ మూడు నెలలుగా జమ కాలేదు", sample_chip_scholarship: "జాతీయ మెరిట్ స్కాలర్‌షిప్ పంపిణీ ఆలస్యం మరియు మంజూరు ఉత్తర్వు", sample_chip_water: "మున్సిపల్ నీటి పైప్‌లైన్ తనిఖీ నివేదిక మరియు కాలక్రమం", your_records: "మీ రికార్డులు", records_count: "3 రికార్డులు", item_road_title: "వార్డు 4 రోడ్డు టెండర్ మంజూరు", item_road_dept: "పబ్లిక్ వర్క్స్ డిపార్ట్‌మెంట్ (PWD)", item_scholarship_title: "జాతీయ మెరిట్ స్కాలర్‌షిప్ విడుదల ఉత్తర్వు", item_scholarship_dept: "విద్యా మంత్రిత్వ శాఖ", item_water_title: "మున్సిపల్ నీటి సరఫరా నాణ్యత నివేదిక", item_water_dept: "మున్సిపల్ కార్పొరేషన్", built_for_clarity: "స్పష్టత కోసం నిర్మించబడింది",
  },
  mr: {
    portal_title: "नागरिक सेवा पोर्टल", brand_title: "आरटीआय सारथी", header_subtitle: "नागरिक माहिती आणि आरटीआय अर्ज प्रणाली", checks_enabled: "अचूक नियम तपासणी सक्रिय", about: "आरटीआय सारथी बद्दल", live_alert_badge: "थेट सूचना", live_alert: "वैधानिक इशारा: कलम 7(1) नुसार 30 दिवसांच्या आत उत्तर देणे बंधनकारक आहे. आधार किंवा पॅन क्रमांक जोडू नका.", screen_1_badge: "स्क्रीन 1 / प्रश्न विचारा", hero_title: "सरकारला स्पष्टपणे विचारा.", hero_sub: "सोप्या भाषेतील प्रश्नांचे सर्व विभागांसाठी संरचित, कायदेशीरदृष्ट्या प्रभावी आरटीआय अर्जांमध्ये रूपांतर करा.", input_label: "तुम्हाला काय जाणून घ्यायचे आहे?", placeholder: "उदाहरण: प्रभाग 4 मधील रस्ता दुरुस्ती निविदेची स्थिती काय आहे किंवा माझी गुणवत्ता शिष्यवृत्ती का रखडली आहे?", btn_continue: "पुढे जा", btn_analyze: "अर्जाचे विश्लेषण करा", need_more_detail: "अधिक तपशील जोडा", question_clear: "प्रश्न स्पष्ट आहे", validation_clear_detail: "यामध्ये सार्वजनिक नोंदीचा विषय आणि नोंदी शोधण्यासाठी पुरेसा तपशील आहे.", recent_inquiries: "अलीकडील सार्वजनिक चौकशी", clarity_card: "प्रत्येक उत्तर तपासता येणाऱ्या प्रश्नाने आणि स्पष्ट स्रोताने सुरू होते.", faq_desk_btn: "💬 आरटीआय मदत कक्ष", try_sample: "एक नमुना वापरून पहा", sample_chip_road: "प्रभाग 4 मधील रस्ता दुरुस्ती निविदेची स्थिती आणि कंत्राटदाराच्या फाइल नोंदी", sample_chip_pension: "माझी पेन्शन तीन महिन्यांपासून जमा झालेली नाही", sample_chip_scholarship: "राष्ट्रीय गुणवत्ता शिष्यवृत्ती वितरणातील विलंब आणि मंजुरी आदेश", sample_chip_water: "महानगरपालिका जलवाहिनी तपासणी अहवाल आणि कालमर्यादा", your_records: "तुमच्या नोंदी", records_count: "3 नोंदी", item_road_title: "प्रभाग 4 रस्ता निविदा मंजुरी", item_road_dept: "सार्वजनिक बांधकाम विभाग (PWD)", item_scholarship_title: "राष्ट्रीय गुणवत्ता शिष्यवृत्ती वितरण आदेश", item_scholarship_dept: "शिक्षण मंत्रालय", item_water_title: "महानगरपालिका पाणीपुरवठा गुणवत्ता अहवाल", item_water_dept: "महानगरपालिका", built_for_clarity: "स्पष्टतेसाठी निर्मित",
  },
  ta: {
    portal_title: "குடிமக்கள் சேவை இணையதளம்", brand_title: "ஆர்டிஐ சாரதி", header_subtitle: "குடிமக்கள் தகவல் மற்றும் ஆர்டிஐ தாக்கல் தளம்", checks_enabled: "துல்லியமான விதி சரிபார்ப்பு செயலில்", about: "ஆர்டிஐ சாரதி பற்றி", live_alert_badge: "நேரடி எச்சரிக்கை", live_alert: "சட்டப்பூர்வ எச்சரிக்கை: பிரிவு 7(1) இன் கீழ் 30 நாட்களுக்குள் பதிலளிக்க வேண்டும். ஆதார் அல்லது பான் எண்களை இணைக்க வேண்டாம்.", screen_1_badge: "திரை 1 / கேள்வி கேளுங்கள்", hero_title: "அரசிடம் தெளிவாகக் கேளுங்கள்.", hero_sub: "எளிய மொழிக் கேள்விகளை அனைத்து துறைகளுக்குமான கட்டமைக்கப்பட்ட, சட்டப்பூர்வ ஆர்டிஐ கோரிக்கைகளாக மாற்றுங்கள்.", input_label: "நீங்கள் எதைத் தெரிந்துகொள்ள விரும்புகிறீர்கள்?", placeholder: "உதாரணம்: வார்டு 4 சாலைப் பணிக்கான ஒப்பந்த நிலை என்ன, அல்லது எனது தகுதி உதவித்தொகை ஏன் தாமதமானது?", btn_continue: "தொடரவும்", btn_analyze: "கோரிக்கையை பகுப்பாய்வு செய்க", need_more_detail: "மேலும் விவரங்களைச் சேர்க்கவும்", question_clear: "கேள்வி தெளிவாக உள்ளது", validation_clear_detail: "இதில் பொது பதிவுத் தலைப்பும் பதிவுகளைத் தேடுவதற்கான போதுமான விவரமும் உள்ளன.", recent_inquiries: "சமீபத்திய பொது விசாரணைகள்", clarity_card: "ஒவ்வொரு பதிலும் சரிபார்க்கக்கூடிய கேள்வி மற்றும் தெளிவான ஆதாரத்துடன் தொடங்குகிறது.", faq_desk_btn: "💬 ஆர்டிஐ உதவி மையம்", try_sample: "மாதிரியை முயற்சிக்கவும்", sample_chip_road: "வார்டு 4 சாலைப் பணிக்கான ஒப்பந்த நிலை மற்றும் ஒப்பந்ததாரர் கோப்பு குறிப்புகள்", sample_chip_pension: "எனது ஓய்வூதியம் மூன்று மாதங்களாக வரவு வைக்கப்படவில்லை", sample_chip_scholarship: "தேசிய தகுதி உதவித்தொகை வழங்கல் தாமதம் மற்றும் அனுமதி ஆணை", sample_chip_water: "நகராட்சி நீர்க்குழாய் ஆய்வு அறிக்கை மற்றும் காலக்கெடு", your_records: "உங்கள் பதிவுகள்", records_count: "3 பதிவுகள்", item_road_title: "வார்டு 4 சாலை ஒப்பந்த அனுமதி", item_road_dept: "பொதுப்பணித் துறை (PWD)", item_scholarship_title: "தேசிய தகுதி உதவித்தொகை வழங்கல் ஆணை", item_scholarship_dept: "கல்வி அமைச்சகம்", item_water_title: "நகராட்சி நீர் வழங்கல் தர அறிக்கை", item_water_dept: "நகராட்சி கழகம்", built_for_clarity: "தெளிவுக்காக உருவாக்கப்பட்டது",
  },
  gu: {
    portal_title: "નાગરિક સેવા પોર્ટલ", brand_title: "આરટીઆઈ સારથી", header_subtitle: "નાગરિક માહિતી અને આરટીઆઈ અરજી સ્તર", checks_enabled: "ચોક્કસ નિયમ તપાસ સક્રિય", about: "આરટીઆઈ સારથી વિશે", live_alert_badge: "લાઇવ ચેતવણી", live_alert: "વૈધાનિક ચેતવણી: કલમ 7(1) હેઠળ 30 દિવસમાં જવાબ આપવો ફરજિયાત છે. આધાર અથવા પાન નંબર જોડશો નહીં.", screen_1_badge: "સ્ક્રીન 1 / પ્રશ્ન પૂછો", hero_title: "સરકારને સ્પષ્ટતા સાથે પૂછો.", hero_sub: "સાદી ભાષાના પ્રશ્નોને તમામ વિભાગો માટે સુવ્યવસ્થિત, કાયદેસર આરટીઆઈ અરજીઓમાં ફેરવો.", input_label: "તમે શું જાણવા માંગો છો?", placeholder: "ઉદાહરણ: વોર્ડ 4માં રસ્તાના સમારકામના ટેન્ડરની સ્થિતિ શું છે અથવા મારી મેરિટ શિષ્યવૃત્તિમાં વિલંબ કેમ છે?", btn_continue: "ચાલુ રાખો", btn_analyze: "અરજીનું વિશ્લેષણ કરો", need_more_detail: "વધુ વિગતો ઉમેરો", question_clear: "પ્રશ્ન સ્પષ્ટ છે", validation_clear_detail: "તેમાં જાહેર રેકોર્ડનો વિષય અને રેકોર્ડ શોધવા માટે પૂરતી વિગતો છે.", recent_inquiries: "તાજેતરની જાહેર પૂછપરછ", clarity_card: "દરેક જવાબ ચકાસી શકાય તેવા પ્રશ્ન અને સ્પષ્ટ સ્રોતથી શરૂ થાય છે.", faq_desk_btn: "💬 આરટીઆઈ મદદ ડેસ્ક", try_sample: "એક નમૂનો અજમાવો", sample_chip_road: "વોર્ડ 4 રસ્તા સમારકામ ટેન્ડરની સ્થિતિ અને કોન્ટ્રાક્ટરની ફાઇલ નોંધો", sample_chip_pension: "મારી પેન્શન ત્રણ મહિનાથી જમા થઈ નથી", sample_chip_scholarship: "રાષ્ટ્રીય મેરિટ શિષ્યવૃત્તિ વિતરણમાં વિલંબ અને મંજૂરી હુકમ", sample_chip_water: "મ્યુનિસિપલ પાણીની પાઇપલાઇન નિરીક્ષણ અહેવાલ અને સમયરેખા", your_records: "તમારા રેકોર્ડ્સ", records_count: "3 રેકોર્ડ્સ", item_road_title: "વોર્ડ 4 રોડ ટેન્ડર મંજૂરી", item_road_dept: "જાહેર બાંધકામ વિભાગ (PWD)", item_scholarship_title: "રાષ્ટ્રીય મેરિટ શિષ્યવૃત્તિ પ્રકાશન હુકમ", item_scholarship_dept: "શિક્ષણ મંત્રાલય", item_water_title: "મ્યુનિસિપલ પાણી પુરવઠા ગુણવત્તા અહેવાલ", item_water_dept: "મ્યુનિસિપલ કોર્પોરેશન", built_for_clarity: "સ્પષ્ટતા માટે નિર્મિત",
  },
  kn: {
    portal_title: "ನಾಗರಿಕ ಸೇವಾ ಪೋರ್ಟಲ್", brand_title: "ಆರ್‌ಟಿಐ ಸಾರಥಿ", header_subtitle: "ನಾಗರಿಕ ಮಾಹಿತಿ ಮತ್ತು ಆರ್‌ಟಿಐ ಸಲ್ಲಿಕೆ ಪದರ", checks_enabled: "ನಿಖರ ನಿಯಮ ಪರಿಶೀಲನೆ ಸಕ್ರಿಯ", about: "ಆರ್‌ಟಿಐ ಸಾರಥಿ ಬಗ್ಗೆ", live_alert_badge: "ನೇರ ಎಚ್ಚರಿಕೆ", live_alert: "ಶಾಸನಬದ್ಧ ಎಚ್ಚರಿಕೆ: ಕಲಂ 7(1) ಅಡಿಯಲ್ಲಿ 30 ದಿನಗಳಲ್ಲಿ ಉತ್ತರಿಸುವುದು ಕಡ್ಡಾಯ. ಆಧಾರ್ ಅಥವಾ ಪಾನ್ ಸಂಖ್ಯೆಗಳನ್ನು ಲಗತ್ತಿಸಬೇಡಿ.", screen_1_badge: "ಸ್ಕ್ರೀನ್ 1 / ಪ್ರಶ್ನೆ ಕೇಳಿ", hero_title: "ಸರ್ಕಾರವನ್ನು ಸ್ಪಷ್ಟವಾಗಿ ಕೇಳಿ.", hero_sub: "ಸರಳ ಭಾಷೆಯ ಪ್ರಶ್ನೆಗಳನ್ನು ಎಲ್ಲಾ ಇಲಾಖೆಗಳಿಗಾಗಿ ರಚನಾತ್ಮಕ, ಕಾನೂನುಬದ್ಧ ಆರ್‌ಟಿಐ ವಿನಂತಿಗಳಾಗಿ ಪರಿವರ್ತಿಸಿ.", input_label: "ನೀವು ಏನು ತಿಳಿದುಕೊಳ್ಳಲು ಬಯಸುತ್ತೀರಿ?", placeholder: "ಉದಾಹರಣೆ: ವಾರ್ಡ್ 4ರ ರಸ್ತೆ ದುರಸ್ತಿ ಟೆಂಡರ್ ಸ್ಥಿತಿ ಏನು ಅಥವಾ ನನ್ನ ಮೆರಿಟ್ ವಿದ್ಯಾರ್ಥಿವೇತನ ಏಕೆ ವಿಳಂಬವಾಗಿದೆ?", btn_continue: "ಮುಂದುವರಿಸಿ", btn_analyze: "ವಿನಂತಿಯನ್ನು ವಿಶ್ಲೇಷಿಸಿ", need_more_detail: "ಹೆಚ್ಚಿನ ವಿವರ ಸೇರಿಸಿ", question_clear: "ಪ್ರಶ್ನೆ ಸ್ಪಷ್ಟವಾಗಿದೆ", validation_clear_detail: "ಇದು ಸಾರ್ವಜನಿಕ ದಾಖಲೆ ವಿಷಯ ಮತ್ತು ದಾಖಲೆಗಳನ್ನು ಹುಡುಕಲು ಸಾಕಷ್ಟು ವಿವರಗಳನ್ನು ಒಳಗೊಂಡಿದೆ.", recent_inquiries: "ಇತ್ತೀಚಿನ ಸಾರ್ವಜನಿಕ ವಿಚಾರಣೆಗಳು", clarity_card: "ಪ್ರತಿ ಉತ್ತರವು ಪರಿಶೀಲಿಸಬಹುದಾದ ಪ್ರಶ್ನೆ ಮತ್ತು ಸ್ಪಷ್ಟ ಮೂಲದಿಂದ ಪ್ರಾರಂಭವಾಗುತ್ತದೆ.", faq_desk_btn: "💬 ಆರ್‌ಟಿಐ ಸಹಾಯವಾಣಿ", try_sample: "ಮಾದರಿಯನ್ನು ಪ್ರಯತ್ನಿಸಿ", sample_chip_road: "ವಾರ್ಡ್ 4 ರಸ್ತೆ ದುರಸ್ತಿ ಟೆಂಡರ್ ಸ್ಥಿತಿ ಮತ್ತು ಗುತ್ತಿಗೆದಾರರ ಕಡತ ಟಿಪ್ಪಣಿಗಳು", sample_chip_pension: "ನನ್ನ ಪಿಂಚಣಿ ಮೂರು ತಿಂಗಳಿಂದ ಜಮೆಯಾಗಿಲ್ಲ", sample_chip_scholarship: "ರಾಷ್ಟ್ರೀಯ ಮೆರಿಟ್ ವಿದ್ಯಾರ್ಥಿವೇತನ ವಿತರಣೆ ವಿಳಂಬ ಮತ್ತು ಮಂಜೂರಾತಿ ಆದೇಶ", sample_chip_water: "ಪುರಸಭೆ ನೀರಿನ ಪೈಪ್‌ಲೈನ್ ತಪಾಸಣೆ ವರದಿ ಮತ್ತು ಕಾಲಮಿತಿ", your_records: "ನಿಮ್ಮ ದಾಖಲೆಗಳು", records_count: "3 ದಾಖಲೆಗಳು", item_road_title: "ವಾರ್ಡ್ 4 ರಸ್ತೆ ಟೆಂಡರ್ ಮಂಜೂರಾತಿ", item_road_dept: "ಸಾರ್ವಜನಿಕ ಕಾಮಗಾರಿ ಇಲಾಖೆ (PWD)", item_scholarship_title: "ರಾಷ್ಟ್ರೀಯ ಮೆರಿಟ್ ವಿದ್ಯಾರ್ಥಿವೇತನ ಬಿಡುಗಡೆ ಆದೇಶ", item_scholarship_dept: "ಶಿಕ್ಷಣ ಸಚಿವಾಲಯ", item_water_title: "ಪುರಸಭೆ ನೀರು ಸರಬರಾಜು ಗುಣಮಟ್ಟ ವರದಿ", item_water_dept: "ಪುರಸಭೆ ನಿಗಮ", built_for_clarity: "ಸ್ಪಷ್ಟತೆಗಾಗಿ ನಿರ್ಮಿಸಲಾಗಿದೆ",
  },
  ml: {
    portal_title: "പൗര സേവന പോർട്ടൽ", brand_title: "ആർടിഐ സാരഥി", header_subtitle: "പൗര വിവരങ്ങളും ആർടിഐ സമർപ്പണ സംവിധാനവും", checks_enabled: "കൃത്യമായ നിയമ പരിശോധന സജീവം", about: "ആർടിഐ സാരഥിയെക്കുറിച്ച്", live_alert_badge: "തത്സമയ മുന്നറിയിപ്പ്", live_alert: "നിയമപരമായ മുന്നറിയിപ്പ്: സെക്ഷൻ 7(1) പ്രകാരം 30 ദിവസത്തിനകം മറുപടി നൽകണം. ആധാർ അല്ലെങ്കിൽ പാൻ നമ്പറുകൾ നൽകരുത്.", screen_1_badge: "സ്ക്രീൻ 1 / ഒരു ചോദ്യം ചോദിക്കുക", hero_title: "സർക്കാരിനോട് വ്യക്തമായി ചോദിക്കൂ.", hero_sub: "ലളിതമായ ഭാഷയിലെ ചോദ്യങ്ങളെ എല്ലാ വകുപ്പുകൾക്കുമുള്ള ഘടനാപരവും നിയമപരവുമായ ആർടിഐ അഭ്യർത്ഥനകളാക്കി മാറ്റുക.", input_label: "നിങ്ങൾ എന്താണ് അറിയാൻ ആഗ്രഹിക്കുന്നത്?", placeholder: "ഉദാഹരണം: വാർഡ് 4 റോഡ് അറ്റകുറ്റപ്പണി ടെൻഡറിന്റെ സ്ഥിതി എന്താണ്, അല്ലെങ്കിൽ എന്റെ മെറിറ്റ് സ്കോളർഷിപ്പ് വൈകിയത് എന്തുകൊണ്ട്?", btn_continue: "തുടരുക", btn_analyze: "അഭ്യർത്ഥന വിശകലനം ചെയ്യുക", need_more_detail: "കൂടുതൽ വിശദാംശങ്ങൾ ചേർക്കുക", question_clear: "ചോദ്യം വ്യക്തമാണ്", validation_clear_detail: "ഇതിൽ പൊതു രേഖാ വിഷയവും രേഖകൾ തിരയാൻ മതിയായ വിശദാംശങ്ങളും ഉണ്ട്.", recent_inquiries: "സമീപകാല പൊതു അന്വേഷണങ്ങൾ", clarity_card: "ഓരോ ഉത്തരവും പരിശോധിക്കാവുന്ന ചോദ്യത്തിലും വ്യക്തമായ ഉറവിടത്തിലും തുടങ്ങുന്നു.", faq_desk_btn: "💬 ആർടിഐ സഹായകേന്ദ്രം", try_sample: "ഒരു മാതൃക പരീക്ഷിക്കുക", sample_chip_road: "വാർഡ് 4 റോഡ് അറ്റകുറ്റപ്പണി ടെൻഡർ സ്ഥിതിയും കരാറുകാരന്റെ ഫയൽ കുറിപ്പുകളും", sample_chip_pension: "എന്റെ പെൻഷൻ മൂന്ന് മാസമായി ക്രെഡിറ്റ് ചെയ്തിട്ടില്ല", sample_chip_scholarship: "ദേശീയ മെറിറ്റ് സ്കോളർഷിപ്പ് വിതരണത്തിലെ കാലതാമസവും അനുമതി ഉത്തരവും", sample_chip_water: "മുനിസിപ്പൽ ജല പൈപ്പ്‌ലൈൻ പരിശോധനാ റിപ്പോർട്ടും സമയക്രമവും", your_records: "നിങ്ങളുടെ രേഖകൾ", records_count: "3 രേഖകൾ", item_road_title: "വാർഡ് 4 റോഡ് ടെൻഡർ അനുമതി", item_road_dept: "പൊതുമരാമത്ത് വകുപ്പ് (PWD)", item_scholarship_title: "ദേശീയ മെറിറ്റ് സ്കോളർഷിപ്പ് റിലീസ് ഓർഡർ", item_scholarship_dept: "വിദ്യാഭ്യാസ മന്ത്രാലയം", item_water_title: "മുനിസിപ്പൽ ജലവിതരണ ഗുണനിലവാര റിപ്പോർട്ട്", item_water_dept: "മുനിസിപ്പൽ കോർപ്പറേഷൻ", built_for_clarity: "വ്യക്തതയ്ക്കായി നിർമ്മിച്ചത്",
  },
  pa: {
    portal_title: "ਨਾਗਰਿਕ ਸੇਵਾ ਪੋਰਟਲ", brand_title: "ਆਰਟੀਆਈ ਸਾਰਥੀ", header_subtitle: "ਨਾਗਰਿਕ ਜਾਣਕਾਰੀ ਅਤੇ ਆਰਟੀਆਈ ਅਰਜ਼ੀ ਪ੍ਰਣਾਲੀ", checks_enabled: "ਸਹੀ ਨਿਯਮ ਜਾਂਚ ਸਰਗਰਮ", about: "ਆਰਟੀਆਈ ਸਾਰਥੀ ਬਾਰੇ", live_alert_badge: "ਲਾਈਵ ਚੇਤਾਵਨੀ", live_alert: "ਕਾਨੂੰਨੀ ਚੇਤਾਵਨੀ: ਧਾਰਾ 7(1) ਅਧੀਨ 30 ਦਿਨਾਂ ਵਿੱਚ ਜਵਾਬ ਦੇਣਾ ਲਾਜ਼ਮੀ ਹੈ। ਆਧਾਰ ਜਾਂ ਪੈਨ ਨੰਬਰ ਨੱਥੀ ਨਾ ਕਰੋ।", screen_1_badge: "ਸਕ੍ਰੀਨ 1 / ਸਵਾਲ ਪੁੱਛੋ", hero_title: "ਸਰਕਾਰ ਨੂੰ ਸਪਸ਼ਟਤਾ ਨਾਲ ਪੁੱਛੋ।", hero_sub: "ਸਧਾਰਨ ਭਾਸ਼ਾ ਦੇ ਸਵਾਲਾਂ ਨੂੰ ਸਾਰੇ ਵਿਭਾਗਾਂ ਲਈ ਢਾਂਚੇਬੱਧ, ਕਾਨੂੰਨੀ ਆਰਟੀਆਈ ਬੇਨਤੀਆਂ ਵਿੱਚ ਬਦਲੋ।", input_label: "ਤੁਸੀਂ ਕੀ ਜਾਣਨਾ ਚਾਹੁੰਦੇ ਹੋ?", placeholder: "ਉਦਾਹਰਨ: ਵਾਰਡ 4 ਵਿੱਚ ਸੜਕ ਮੁਰੰਮਤ ਟੈਂਡਰ ਦੀ ਸਥਿਤੀ ਕੀ ਹੈ ਜਾਂ ਮੇਰੀ ਮੈਰਿਟ ਸਕਾਲਰਸ਼ਿਪ ਵਿੱਚ ਦੇਰੀ ਕਿਉਂ ਹੈ?", btn_continue: "ਜਾਰੀ ਰੱਖੋ", btn_analyze: "ਬੇਨਤੀ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰੋ", need_more_detail: "ਹੋਰ ਵੇਰਵੇ ਸ਼ਾਮਲ ਕਰੋ", question_clear: "ਸਵਾਲ ਸਪਸ਼ਟ ਹੈ", validation_clear_detail: "ਇਸ ਵਿੱਚ ਜਨਤਕ ਰਿਕਾਰਡ ਦਾ ਵਿਸ਼ਾ ਅਤੇ ਰਿਕਾਰਡ ਲੱਭਣ ਲਈ ਕਾਫ਼ੀ ਵੇਰਵਾ ਹੈ।", recent_inquiries: "ਹਾਲੀਆ ਜਨਤਕ ਪੁੱਛਗਿੱਛ", clarity_card: "ਹਰ ਜਵਾਬ ਇੱਕ ਜਾਂਚਯੋਗ ਸਵਾਲ ਅਤੇ ਸਪਸ਼ਟ ਸਰੋਤ ਤੋਂ ਸ਼ੁਰੂ ਹੁੰਦਾ ਹੈ।", faq_desk_btn: "💬 ਆਰਟੀਆਈ ਮਦਦ ਡੈਸਕ", try_sample: "ਇੱਕ ਨਮੂਨਾ ਅਜ਼ਮਾਓ", sample_chip_road: "ਵਾਰਡ 4 ਵਿੱਚ ਸੜਕ ਮੁਰੰਮਤ ਟੈਂਡਰ ਦੀ ਸਥਿਤੀ ਅਤੇ ਠੇਕੇਦਾਰ ਦੀ ਫਾਈਲ ਨੋਟਿੰਗ", sample_chip_pension: "ਮੇਰੀ ਪੈਨਸ਼ਨ ਤਿੰਨ ਮਹੀਨਿਆਂ ਤੋਂ ਜਮ੍ਹਾਂ ਨਹੀਂ ਹੋਈ", sample_chip_scholarship: "ਰਾਸ਼ਟਰੀ ਮੈਰਿਟ ਸਕਾਲਰਸ਼ਿਪ ਵੰਡ ਵਿੱਚ ਦੇਰੀ ਅਤੇ ਮਨਜ਼ੂਰੀ ਹੁਕਮ", sample_chip_water: "ਨਗਰ ਪਾਣੀ ਪਾਈਪਲਾਈਨ ਜਾਂਚ ਰਿਪੋਰਟ ਅਤੇ ਸਮਾਂ-ਸੀਮਾ", your_records: "ਤੁਹਾਡੇ ਰਿਕਾਰਡ", records_count: "3 ਰਿਕਾਰਡ", item_road_title: "ਵਾਰਡ 4 ਸੜਕ ਟੈਂਡਰ ਮਨਜ਼ੂਰੀ", item_road_dept: "ਲੋਕ ਨਿਰਮਾਣ ਵਿਭਾਗ (PWD)", item_scholarship_title: "ਰਾਸ਼ਟਰੀ ਮੈਰਿਟ ਸਕਾਲਰਸ਼ਿਪ ਜਾਰੀ ਹੁਕਮ", item_scholarship_dept: "ਸਿੱਖਿਆ ਮੰਤਰਾਲਾ", item_water_title: "ਨਗਰ ਪਾਣੀ ਸਪਲਾਈ ਗੁਣਵੱਤਾ ਰਿਪੋਰਟ", item_water_dept: "ਨਗਰ ਨਿਗਮ", built_for_clarity: "ਸਪਸ਼ਟਤਾ ਲਈ ਬਣਾਇਆ ਗਿਆ",
  },
};

interface LanguageContextValue { language: LanguageCode; setLanguage: (language: LanguageCode) => void; t: (key: TranslationKey) => string; }
const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<LanguageCode>("en");

  useEffect(() => {
    const saved = window.localStorage.getItem("rti_lang") as LanguageCode | null;
    if (saved && saved in translations) {
      const restore = window.setTimeout(() => setLanguageState(saved), 0);
      return () => window.clearTimeout(restore);
    }
  }, []);

  function setLanguage(next: LanguageCode) {
    setLanguageState(next in translations ? next : "en");
    window.localStorage.setItem("rti_lang", next in translations ? next : "en");
  }

  const value = useMemo(() => ({ language, setLanguage, t: (key: TranslationKey) => translations[language][key] }), [language]);
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
}
